[package]
name = "dice-mfg"
version = "0.1.0"
edition = "2021"
description = "A command line tool for creating and programming device identities for Oxide RoTs."
license = "MPL-2.0"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4", features = ["derive", "env"] }
dice-mfg-msgs = { path = "../dice-mfg-msgs" }
env_logger = "0.9"
log = "0.4"
pem-rfc7468 = { version = "0.7.0", features = ["alloc", "std"] }
serialport = "4"
string-error = "0.1"
tempfile = "3.3"
zerocopy = "0.6"
